##Creating Tensors using Tensorflow and manipulating it.

In [ ]:
# Use of tf.constant()

In [3]:
import tensorflow as tf
print(tf.__version__)

2.6.0


In [5]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
scalar.ndim

0

In [7]:
vector = tf.constant([3,5])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5], dtype=int32)>

In [8]:
vector.ndim

1

In [9]:
matrix = tf.constant([[3,4],[6,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [6, 7]], dtype=int32)>

In [10]:
matrix.ndim

2

In [12]:
matrix_2 = tf.constant([[2,3],[4,6]], dtype = tf.float16) #float takes less space in RAM than int
matrix_2

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[2., 3.],
       [4., 6.]], dtype=float16)>

In [13]:
# Use of tf.Variable()

In [16]:
changeable_tensor = tf.Variable([7,8])
unchangeable_tensor = tf.constant([9,8])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 8], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([9, 8], dtype=int32)>)

In [17]:
changeable_tensor[0].assign(10)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([10,  8], dtype=int32)>

In [20]:
#we can't change the value of tf.constant

unchangeable_tensor[0].assign(34)

AttributeError: ignored

In [25]:
# Random Tensors

randomT_1 = tf.random.Generator.from_seed(23)
randomT_1 = randomT_1.normal(shape = (3,3))

randomT_2 = tf.random.Generator.from_seed(23)
randomT_2 = randomT_2.normal(shape = (3,3))

randomT_1, randomT_2

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.1175475 ,  0.03493892, -1.5700307 ],
        [ 0.4457582 ,  0.10944034, -0.8035768 ],
        [-1.7166729 ,  0.3738578 , -0.14371012]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[ 0.1175475 ,  0.03493892, -1.5700307 ],
        [ 0.4457582 ,  0.10944034, -0.8035768 ],
        [-1.7166729 ,  0.3738578 , -0.14371012]], dtype=float32)>)

In [28]:
randomT_3 = tf.random.uniform(shape = (2,2),minval = 1, maxval = 10)
randomT_3

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4.7865133, 6.8554306],
       [3.033843 , 7.0938835]], dtype=float32)>

In [29]:
# Creating tensors using NumPy

tf.ones([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [30]:
tf.zeros([2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [31]:
import numpy as np

In [36]:
npA = np.arange(1,21)
npA

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [39]:
np_tensorA = tf.constant(npA, shape = (5,2,2))

In [40]:
np_tensorA 


<tf.Tensor: shape=(5, 2, 2), dtype=int64, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]]])>

In [41]:
# One hot encoding

In [44]:
list = [0,1,2,3]

tf.one_hot(list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [45]:
tf.one_hot(list, depth = 4, on_value = 'YES', off_value = 'NO')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'YES', b'NO', b'NO', b'NO'],
       [b'NO', b'YES', b'NO', b'NO'],
       [b'NO', b'NO', b'YES', b'NO'],
       [b'NO', b'NO', b'NO', b'YES']], dtype=object)>

In [46]:
tf.one_hot(list, depth = 3)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]], dtype=float32)>

In [4]:
# Math operations
list  = [7,9,3,5]
list_tensor = tf.constant(list)

In [5]:
tf.square(list_tensor)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([49, 81,  9, 25], dtype=int32)>

In [7]:
tf.sqrt(tf.cast(list_tensor, dtype = tf.float16))

<tf.Tensor: shape=(4,), dtype=float16, numpy=array([2.646, 3.   , 1.732, 2.236], dtype=float16)>

In [10]:
tf.math.log(tf.cast(list_tensor, dtype = tf.float16))

<tf.Tensor: shape=(4,), dtype=float16, numpy=array([1.946, 2.197, 1.099, 1.609], dtype=float16)>

In [12]:
tf.math.sigmoid(tf.cast(list_tensor, dtype = tf.float16))

<tf.Tensor: shape=(4,), dtype=float16, numpy=array([0.999 , 1.    , 0.9526, 0.993 ], dtype=float16)>

In [13]:
# Access to GPU

In [1]:
import tensorflow as tf
tf.config.list_physical_devices() 

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [2]:
!nvidia-smi

Thu Sep  9 15:38:22 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.63.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8    31W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------